# -*- coding: utf-8 -*-
"""导入示例词库到数据库。

使用：python seed.py
可重复执行：已存在的英文单词会被跳过。
"""
from app import app, db
from models import Word

# 示例词库（英文, 音标, 中文）
SAMPLE_WORDS = [
    ('abandon', '/əˈbændən/', 'vt. 放弃；抛弃'),
    ('ability', '/əˈbɪləti/', 'n. 能力；才能'),
    ('abroad', '/əˈbrɔːd/', 'adv. 在国外；到国外'),
    ('absence', '/ˈæbsəns/', 'n. 缺席；缺乏'),
    ('absolute', '/ˈæbsəluːt/', 'adj. 绝对的；完全的'),
    ('academic', '/ˌækəˈdemɪk/', 'adj. 学术的；学院的'),
    ('accept', '/əkˈsept/', 'v. 接受；同意'),
    ('access', '/ˈækses/', 'n. 进入；访问；通道'),
    ('accident', '/ˈæksɪdənt/', 'n. 事故；意外'),
    ('accomplish', '/əˈkʌmplɪʃ/', 'vt. 完成；实现'),
    ('account', '/əˈkaʊnt/', 'n. 账户；账目；描述'),
    ('accurate', '/ˈækjərət/', 'adj. 精确的；准确的'),
    ('achieve', '/əˈtʃiːv/', 'vt. 实现；达到'),
    ('acquire', '/əˈkwaɪər/', 'vt. 获得；学到'),
    ('actual', '/ˈæktʃuəl/', 'adj. 真实的；实际的'),
    ('adapt', '/əˈdæpt/', 'v. 适应；改编'),
    ('addition', '/əˈdɪʃn/', 'n. 增加；加法'),
    ('adequate', '/ˈædɪkwət/', 'adj. 充足的；适当的'),
    ('adjust', '/əˈdʒʌst/', 'v. 调整；适应'),
    ('administration', '/ədˌmɪnɪˈstreɪʃn/', 'n. 管理；行政'),
    ('adopt', '/əˈdɒpt/', 'vt. 采取；收养'),
    ('advanced', '/ədˈvɑːnst/', 'adj. 先进的；高级的'),
    ('advantage', '/ədˈvɑːntɪdʒ/', 'n. 优势；有利条件'),
    ('advertise', '/ˈædvətaɪz/', 'v. 做广告；宣传'),
    ('advice', '/ədˈvaɪs/', 'n. 建议；忠告'),
    ('affect', '/əˈfekt/', 'vt. 影响；感动'),
    ('afford', '/əˈfɔːd/', 'vt. 买得起；承担得起'),
    ('agency', '/ˈeɪdʒənsi/', 'n. 代理；机构'),
    ('aggressive', '/əˈɡresɪv/', 'adj. 侵略性的；积极进取的'),
    ('aim', '/eɪm/', 'n. 目标；v. 瞄准；旨在'),
    ('analysis', '/əˈnæləsɪs/', 'n. 分析'),
    ('ancient', '/ˈeɪnʃənt/', 'adj. 古老的；古代的'),
    ('announce', '/əˈnaʊns/', 'vt. 宣布；通告'),
    ('annual', '/ˈænjuəl/', 'adj. 年度的；每年的'),
    ('anxiety', '/æŋˈzaɪəti/', 'n. 焦虑；担忧'),
    ('apologize', '/əˈpɒlədʒaɪz/', 'vi. 道歉'),
    ('apparent', '/əˈpærənt/', 'adj. 明显的；表面的'),
    ('appeal', '/əˈpiːl/', 'n. 呼吁；吸引力；v. 上诉'),
    ('appreciate', '/əˈpriːʃieɪt/', 'vt. 欣赏；感激'),
    ('approach', '/əˈprəʊtʃ/', 'n. 方法；v. 接近'),
    ('appropriate', '/əˈprəʊpriət/', 'adj. 适当的；合适的'),
    ('approve', '/əˈpruːv/', 'v. 赞成；批准'),
    ('arbitrary', '/ˈɑːbɪtrəri/', 'adj. 任意的；武断的'),
    ('arrange', '/əˈreɪndʒ/', 'v. 安排；排列'),
    ('aspect', '/ˈæspekt/', 'n. 方面；层面'),
    ('assemble', '/əˈsembl/', 'v. 集合；装配'),
    ('assess', '/əˈses/', 'vt. 评估；评定'),
    ('assign', '/əˈsaɪn/', 'vt. 分配；指派'),
    ('assistance', '/əˈsɪstəns/', 'n. 帮助；援助'),
    # ---- 50-100 ----
    ('assume', '/əˈsjuːm/', 'vt. 假定；承担'),
    ('atmosphere', '/ˈætməsfɪər/', 'n. 大气；气氛'),
    ('attach', '/əˈtætʃ/', 'v. 附加；连接'),
    ('attain', '/əˈteɪn/', 'vt. 达到；获得'),
    ('attempt', '/əˈtempt/', 'n./v. 尝试；企图'),
    ('attitude', '/ˈætɪtjuːd/', 'n. 态度；看法'),
    ('attribute', '/əˈtrɪbjuːt/', 'vt. 归因；n. 属性'),
    ('audience', '/ˈɔːdiəns/', 'n. 观众；听众'),
    ('author', '/ˈɔːθər/', 'n. 作者；作家'),
    ('authority', '/ɔːˈθɒrəti/', 'n. 权力；当局'),
    ('automatic', '/ˌɔːtəˈmætɪk/', 'adj. 自动的'),
    ('available', '/əˈveɪləbl/', 'adj. 可用的；可获得的'),
    ('average', '/ˈævərɪdʒ/', 'n. 平均；adj. 平均的'),
    ('aware', '/əˈweər/', 'adj. 意识到的；知道的'),
    ('balance', '/ˈbæləns/', 'n. 平衡；v. 使平衡'),
    ('ban', '/bæn/', 'vt. 禁止；n. 禁令'),
    ('barrier', '/ˈbæriər/', 'n. 障碍；屏障'),
    ('base', '/beɪs/', 'n. 基础；基地；vt. 以…为基础'),
    ('basis', '/ˈbeɪsɪs/', 'n. 基础；根据'),
    ('benefit', '/ˈbenɪfɪt/', 'n. 利益；好处；v. 受益'),
    ('biology', '/baɪˈɒlədʒi/', 'n. 生物学'),
    ('border', '/ˈbɔːdər/', 'n. 边界；v. 接壤'),
    ('brain', '/breɪn/', 'n. 大脑；智力'),
    ('branch', '/brɑːntʃ/', 'n. 树枝；分支'),
    ('brief', '/briːf/', 'adj. 简短的；vt. 简报'),
    ('broad', '/brɔːd/', 'adj. 宽的；广泛的'),
    ('budget', '/ˈbʌdʒɪt/', 'n. 预算'),
    ('burden', '/ˈbɜːdn/', 'n. 负担；重担'),
    ('calculate', '/ˈkælkjuleɪt/', 'v. 计算；推算'),
    ('campaign', '/kæmˈpeɪn/', 'n. 运动；战役'),
    ('candidate', '/ˈkændɪdət/', 'n. 候选人；应试者'),
    ('capacity', '/kəˈpæsəti/', 'n. 容量；能力'),
    ('capital', '/ˈkæpɪtl/', 'n. 首都；资本；adj. 大写的'),
    ('capture', '/ˈkæptʃər/', 'vt. 捕获；吸引'),
    ('career', '/kəˈrɪər/', 'n. 生涯；职业'),
    ('category', '/ˈkætəgəri/', 'n. 种类；类别'),
    ('cause', '/kɔːz/', 'n. 原因；事业；vt. 引起'),
    ('chain', '/tʃeɪn/', 'n. 链条；连锁'),
    ('challenge', '/ˈtʃælɪndʒ/', 'n. 挑战；vt. 向…挑战'),
    ('channel', '/ˈtʃænl/', 'n. 频道；渠道'),
    ('character', '/ˈkærəktər/', 'n. 性格；字符；人物'),
    ('charge', '/tʃɑːdʒ/', 'v. 收费；充电；n. 费用；负责'),
    ('chemical', '/ˈkemɪkl/', 'adj. 化学的；n. 化学品'),
    ('circle', '/ˈsɜːkl/', 'n. 圆圈；v. 圈出'),
    ('circumstance', '/ˈsɜːkəmstəns/', 'n. 情况；环境'),
    ('citizen', '/ˈsɪtɪzn/', 'n. 公民；市民'),
    ('civil', '/ˈsɪvl/', 'adj. 公民的；民用的'),
    ('claim', '/kleɪm/', 'v. 声称；要求；n. 主张；索赔'),
    ('classic', '/ˈklæsɪk/', 'adj. 经典的；n. 经典'),
    # ---- 100-150 ----
    ('climate', '/ˈklaɪmət/', 'n. 气候'),
    ('coast', '/kəʊst/', 'n. 海岸'),
    ('collapse', '/kəˈlæps/', 'v./n. 倒塌；崩溃'),
    ('combine', '/kəmˈbaɪn/', 'v. 结合；联合'),
    ('comment', '/ˈkɒment/', 'n. 评论；v. 发表意见'),
    ('commission', '/kəˈmɪʃn/', 'n. 委员会；佣金'),
    ('common', '/ˈkɒmən/', 'adj. 共同的；普通的'),
    ('community', '/kəˈmjuːnəti/', 'n. 社区；共同体'),
    ('compare', '/kəmˈpeər/', 'v. 比较；对照'),
    ('compete', '/kəmˈpiːt/', 'vi. 竞争；比赛'),
    ('complex', '/ˈkɒmpleks/', 'adj. 复杂的；n. 综合体'),
    ('concept', '/ˈkɒnsept/', 'n. 概念；观念'),
    ('concern', '/kənˈsɜːn/', 'v. 涉及；使担忧；n. 关心；关切'),
    ('conclude', '/kənˈkluːd/', 'v. 推断出；结束'),
    ('concrete', '/ˈkɒŋkriːt/', 'adj. 具体的；混凝土'),
    ('conduct', '/kənˈdʌkt/', 'vt. 指挥；进行；n. 行为'),
    ('confidence', '/ˈkɒnfɪdəns/', 'n. 信心；信任'),
    ('confirm', '/kənˈfɜːm/', 'vt. 证实；确认'),
    ('conflict', '/ˈkɒnflɪkt/', 'n. 冲突；矛盾'),
    ('confuse', '/kənˈfjuːz/', 'vt. 使困惑；混淆'),
    ('connect', '/kəˈnekt/', 'v. 连接；联系'),
    ('consequence', '/ˈkɒnsɪkwəns/', 'n. 后果；结果'),
    ('conservative', '/kənˈsɜːvətɪv/', 'adj. 保守的；n. 保守者'),
    ('consider', '/kənˈsɪdər/', 'v. 考虑；认为'),
    ('constant', '/ˈkɒnstənt/', 'adj. 不断的；恒定的'),
    ('constitute', '/ˈkɒnstɪtjuːt/', 'vt. 构成；组成'),
    ('construct', '/kənˈstrʌkt/', 'vt. 建造；构筑'),
    ('consume', '/kənˈsjuːm/', 'vt. 消耗；消费'),
    ('contact', '/ˈkɒntækt/', 'n./v. 接触；联系'),
    ('contain', '/kənˈteɪn/', 'vt. 包含；容纳'),
    ('contemporary', '/kənˈtemprəri/', 'adj. 当代的；同时代的'),
    ('content', '/ˈkɒntent/', 'n. 内容；adj. 满足的'),
    ('contest', '/ˈkɒntest/', 'n. 比赛；竞争'),
    ('context', '/ˈkɒntekst/', 'n. 上下文；背景'),
    ('contract', '/ˈkɒntrækt/', 'n. 合同；v. 订合同；收缩'),
    ('contradict', '/ˌkɒntrəˈdɪkt/', 'v. 反驳；矛盾'),
    ('contrast', '/ˈkɒntrɑːst/', 'n. 对比；v. 对照'),
    ('contribute', '/kənˈtrɪbjuːt/', 'v. 贡献；捐助'),
    ('control', '/kənˈtrəʊl/', 'vt. 控制；n. 控制；权力'),
    ('convenience', '/kənˈviːniəns/', 'n. 便利；方便'),
    ('convince', '/kənˈvɪns/', 'vt. 使确信；说服'),
    ('corporate', '/ˈkɔːpərət/', 'adj. 公司的；法人的'),
    ('correct', '/kəˈrekt/', 'adj. 正确的；vt. 改正'),
    ('council', '/ˈkaʊnsl/', 'n. 理事会；委员会'),
    ('count', '/kaʊnt/', 'v. 计数；重要；n. 计数'),
    ('counter', '/ˈkaʊntər/', 'n. 柜台；adj. 相反的'),
    ('country', '/ˈkʌntri/', 'n. 国家；乡村'),
    ('county', '/ˈkaʊnti/', 'n. 县'),
    ('couple', '/ˈkʌpl/', 'n. 一对；夫妻；几个'),
    ('course', '/kɔːs/', 'n. 课程；过程；航线'),
    ('court', '/kɔːt/', 'n. 法庭；球场；庭院'),
    ('cover', '/ˈkʌvər/', 'vt. 覆盖；包括；n. 封面'),
    # ---- 150-200 ----
    ('create', '/kriˈeɪt/', 'vt. 创造；创作'),
    ('credit', '/ˈkredɪt/', 'n. 信用；学分；赞扬'),
    ('crime', '/kraɪm/', 'n. 犯罪；罪行'),
    ('crisis', '/ˈkraɪsɪs/', 'n. 危机；转折点'),
    ('critic', '/ˈkrɪtɪk/', 'n. 批评家；评论家'),
    ('critical', '/ˈkrɪtɪkl/', 'adj. 批评的；关键的'),
    ('culture', '/ˈkʌltʃər/', 'n. 文化；教养'),
    ('current', '/ˈkʌrənt/', 'adj. 当前的；n. 水流；电流'),
    ('daily', '/ˈdeɪli/', 'adj. 每日的；adv. 每日'),
    ('damage', '/ˈdæmɪdʒ/', 'n./vt. 损害；损坏'),
    ('debate', '/dɪˈbeɪt/', 'n./v. 辩论；争论'),
    ('decade', '/ˈdekeɪd/', 'n. 十年'),
    ('decide', '/dɪˈsaɪd/', 'v. 决定；决断'),
    ('decline', '/dɪˈklaɪn/', 'v. 下降；拒绝；n. 衰退'),
    ('declare', '/dɪˈkleər/', 'vt. 宣布；声明'),
    ('decrease', '/dɪˈkriːs/', 'v./n. 减少；降低'),
    ('deep', '/diːp/', 'adj. 深的；深刻的'),
    ('defend', '/dɪˈfend/', 'v. 保卫；辩护'),
    ('define', '/dɪˈfaɪn/', 'vt. 给…下定义；明确'),
    ('delay', '/dɪˈleɪ/', 'n./v. 耽搁；推迟'),
    ('deliver', '/dɪˈlɪvər/', 'vt. 投递；交付；发表'),
    ('demand', '/dɪˈmɑːnd/', 'n. 需求；vt. 要求'),
    ('democracy', '/dɪˈmɒkrəsi/', 'n. 民主；民主政治'),
    ('demonstrate', '/ˈdemənstreɪt/', 'v. 论证；示范；演示'),
    ('depend', '/dɪˈpend/', 'vi. 依赖；取决于'),
    ('design', '/dɪˈzaɪn/', 'n./vt. 设计；构思'),
    ('desire', '/dɪˈzaɪər/', 'n. 欲望；vt. 渴望'),
    ('destroy', '/dɪˈstrɔɪ/', 'vt. 破坏；毁灭'),
    ('detail', '/ˈdiːteɪl/', 'n. 细节；详情'),
    ('determine', '/dɪˈtɜːmɪn/', 'v. 决定；确定'),
    ('develop', '/dɪˈveləp/', 'v. 发展；开发；冲洗'),
    ('device', '/dɪˈvaɪs/', 'n. 装置；设备'),
    ('devote', '/dɪˈvəʊt/', 'vt. 奉献；致力于'),
    ('differ', '/ˈdɪfər/', 'vi. 不同；相异'),
    ('difficulty', '/ˈdɪfɪkəlti/', 'n. 困难；难度'),
    ('dimension', '/daɪˈmenʃn/', 'n. 尺寸；维度'),
    ('direct', '/dəˈrekt/', 'adj. 直接的；vt. 指挥'),
    ('director', '/dəˈrektər/', 'n. 主任；导演；董事'),
    ('disappear', '/ˌdɪsəˈpɪər/', 'vi. 消失；失踪'),
    ('disaster', '/dɪˈzɑːstər/', 'n. 灾难；灾祸'),
    ('discipline', '/ˈdɪsəplɪn/', 'n. 纪律；学科'),
    ('discover', '/dɪˈskʌvər/', 'vt. 发现；找到'),
    ('distance', '/ˈdɪstəns/', 'n. 距离；远方'),
    ('district', '/ˈdɪstrɪkt/', 'n. 区域；地区'),
    ('document', '/ˈdɒkjumənt/', 'n. 文件；文档'),
    ('domestic', '/dəˈmestɪk/', 'adj. 国内的；家庭的'),
    ('dominant', '/ˈdɒmɪnənt/', 'adj. 占优势的；主导的'),
    ('double', '/ˈdʌbl/', 'adj. 双倍的；v. 加倍'),
    ('doubt', '/daʊt/', 'n./v. 怀疑；疑惑'),
    # ---- 200-250 ----
    ('economy', '/ɪˈkɒnəmi/', 'n. 经济；节约'),
    ('editor', '/ˈedɪtər/', 'n. 编辑；编者'),
    ('educate', '/ˈedʒukeɪt/', 'v. 教育；培养'),
    ('effective', '/ɪˈfektɪv/', 'adj. 有效的；起作用的'),
    ('effort', '/ˈefət/', 'n. 努力；尝试'),
    ('election', '/ɪˈlekʃn/', 'n. 选举'),
    ('element', '/ˈelɪmənt/', 'n. 元素；要素'),
    ('emerge', '/ɪˈmɜːdʒ/', 'vi. 出现；浮现'),
    ('emotion', '/ɪˈməʊʃn/', 'n. 情感；情绪'),
    ('emphasis', '/ˈemfəsɪs/', 'n. 强调；重点'),
    ('employ', '/ɪmˈplɔɪ/', 'vt. 雇用；使用'),
    ('encourage', '/ɪnˈkʌrɪdʒ/', 'vt. 鼓励；鼓舞'),
    ('energy', '/ˈenədʒi/', 'n. 能量；精力'),
    ('engage', '/ɪnˈgeɪdʒ/', 'v. 参与；吸引；订婚'),
    ('engine', '/ˈendʒɪn/', 'n. 发动机；引擎'),
    ('enormous', '/ɪˈnɔːməs/', 'adj. 巨大的；庞大的'),
    ('ensure', '/ɪnˈʃʊər/', 'vt. 确保；保证'),
    ('entire', '/ɪnˈtaɪər/', 'adj. 整个的；完全的'),
    ('environment', '/ɪnˈvaɪrənmənt/', 'n. 环境'),
    ('equal', '/ˈiːkwəl/', 'adj. 相等的；vt. 等于'),
    ('equipment', '/ɪˈkwɪpmənt/', 'n. 设备；装备'),
    ('error', '/ˈerər/', 'n. 错误；过失'),
    ('escape', '/ɪˈskeɪp/', 'v./n. 逃跑；逃避'),
    ('essential', '/ɪˈsenʃl/', 'adj. 必要的；本质的'),
    ('establish', '/ɪˈstæblɪʃ/', 'vt. 建立；确立'),
    ('estimate', '/ˈestɪmeɪt/', 'v./n. 估计；估算'),
    ('ethnic', '/ˈeθnɪk/', 'adj. 民族的；种族的'),
    ('evaluate', '/ɪˈvæljueɪt/', 'vt. 评价；评估'),
    ('event', '/ɪˈvent/', 'n. 事件；活动'),
    ('eventually', '/ɪˈventʃuəli/', 'adv. 最终；终于'),
    ('evidence', '/ˈevɪdəns/', 'n. 证据；迹象'),
    ('evolution', '/ˌiːvəˈluːʃn/', 'n. 进化；演变'),
    ('exactly', '/ɪɡˈzæktli/', 'adv. 确切地；恰恰'),
    ('examine', '/ɪɡˈzæmɪn/', 'v. 检查；考察'),
    ('exceed', '/ɪkˈsiːd/', 'vt. 超过；超出'),
    ('exchange', '/ɪksˈtʃeɪndʒ/', 'n./v. 交换；兑换'),
    ('exist', '/ɪɡˈzɪst/', 'vi. 存在；生存'),
    ('expand', '/ɪkˈspænd/', 'v. 扩大；扩展'),
    ('expect', '/ɪkˈspekt/', 'vt. 期待；预期'),
    ('experience', '/ɪkˈspɪəriəns/', 'n. 经验；经历；vt. 体验'),
    ('experiment', '/ɪkˈsperɪmənt/', 'n. 实验；试验'),
    ('expert', '/ˈekspɜːt/', 'n. 专家；adj. 内行的'),
    ('explain', '/ɪkˈspleɪn/', 'v. 解释；说明'),
    ('explore', '/ɪkˈsplɔːr/', 'v. 探索；探险'),
    ('export', '/ɪkˈspɔːt/', 'v./n. 出口；输出'),
    ('expose', '/ɪkˈspəʊz/', 'vt. 暴露；揭露'),
    ('extend', '/ɪkˈstend/', 'v. 延伸；扩大'),
    ('external', '/ɪkˈstɜːnl/', 'adj. 外部的；外在的'),
    ('extreme', '/ɪkˈstriːm/', 'adj. 极端的；n. 极端'),
]


def seed():
    with app.app_context():
        added = 0
        for english, phonetic, chinese in SAMPLE_WORDS:
            if Word.query.filter_by(english=english).first():
                continue
            db.session.add(Word(english=english, chinese=chinese, phonetic=phonetic))
            added += 1
        db.session.commit()
        total = Word.query.count()
        print(f'本次新增 {added} 个单词，词库总计 {total} 个。')


if __name__ == '__main__':
    seed()
